apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- db-claim.yaml
# - vault-secret.yaml # We will apply this manually later

# Also create the service account for the app
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: db-pinger-conn
  type: Opaque
  literals:
  - username=dummy-user
  - password=dummy-password
  - endpoint=dummy-host.example.com
configMapGenerator:
- name: db-pinger-config
  literals:
    - DB_HOST="dummy-host.example.com"
    - DB_PORT="5432"

# Create a service account for the deployment
resources:
- serviceaccount.yaml
