apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All resources are managed through Git
resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

configMapGenerator:
- name: db-pinger-config
  literals:
  # These will be overridden by overlays
  - ENVIRONMENT="base"
  - LOG_LEVEL="info"
